* Aohd
  Jason walks into the Kitchen where Aodh is fring egges with a skillet on his wing. 

Jason laughs and says, "So man do you ever go back to hell to chck in?" Aohd nods and flips the pan up. It does a flip and he catches it back on his wing. JAson laughs and says, "WHat was that?" Aohd replies, "It says, you need to flip the
eggs"

Jason replies shaking his head, "Man your supose to flip the egg not the pan and eggs" 

Aohd is amazed and says, "That makes more since. That's probably why I keep burning them"

Jason looks in to the trash and sees it full of burnt black eggs. He looks at Aohd and says, "How many dozen have you used and how did youget them?" 

Aohd shrugs and says, "I don't know but there is some chickens down the road. Why do they swim in water?" Jason laughs andsyas, "Those are geese man" Aohd laughs and says, "That makes more since. I thought they where chckens the somene 
tried to ring the necks but wasn't succeful so they threw them out"

Aohd looks at his wing and says, "Damn I need to go" Jason is busy laughing. 

As Aohd is walking out the front door he stps and says, "Oh crap. He then slams is and runs to the back one. 

Jason is still laughing. Though Aodh is in panick

At the back door Aohd opens and sees a very tall ox standing there. His eyes are hollow and he's wearing all black. Aohd tries to leave but he hears. 

"Freeze, Aohd"

Aohd turns around and sees the ox trying to get in but can't. The ox looks at Aohd and says, "Invite me in" Aohd grins and says, "What demon's can't just walk in places? Don't you wish you where neautral like me?" 

The demon angry now says, "Let me in" 

"No"< aohd says mockeingly.

The deemon's eyes begin to glow before he says, "I order you let me in", ina deap hollow voice.

Aohd crosses his wings and shakes his head. 

Jason walks up beside him and says, "Why don't you tell him to come on in?"

The ox smiles and says, "Thank you infidel" 

Aohd shakes his head and says, "Nope he was asking a question not inviting"

The ox walks forward but a wall of fire blocks him from entering. Aohd laughs. 

Jason srhgus and says, "Come on" AOhd covers his mouth and pulls him back.

"Man that's a demon. He can't come in unless you ask him to. Literly all teh forces of heavan and hell will prevent him from doing it."

"What's the harm if he does?"

"One he'll get me. two I'll have to go back. three he'll take over your house and there thier the worse kind of free loader. They make the rooms cold and eat all your food and won't leave. 
Jason nods and says, "So what are you going to do? just taunt him until  he gets bored?"

just then there's a knock on the door. Jason answers it and a sheep with wings walks in. After excusing himeself to Jason. Aohd runs to the back door and says, "Not fair man" The demon laughs. Aohd points and says, "Who's this?"

The sheep answers, "I'm Galley. I'm just here to get Aohd outside so he can stand trail. Then I promise I'll leave", in a kind voice" the sheep pushes aohd threw the doorway the demon grabs his arm and wlaks him threw a portal. The sheep 
bows to Jason and says, "To ease your greif your having. Aohd mostly likely won't be terminated. He'll be damned to earth" The sheep then leaves.

* The trail
Aohd stands in front of thee figures wearing black robes with hoods. Aohd is standing on the floor looking up. The one in the middle says, "You've been charged with desertion" The one of his left says, "We're here to decide you punishment"
the one of the far left says, "You did no damage to earth where there. You only took refuge. The power above us has decided that you intend no harm" The one in the middle says, "We are not casting you out. Your punishment though will be
guardian of earth. There are other's like you there. After your term is up on earth you will then be assigned to Sector Phi"

Terror feels Aohd. He speaks up and says, "Sector Phi, can't I be asigne dto Sigma?" The one of the right shakes his head nad says, "NO" the middle one says, "I know heavan isn't the most pleasing place but your to nice"

Aohd is confused and says, "Heaven?" 

The one of the right says, "Yes Sector Phi"

Aohd whispers, "Didn't expect that. Why are peope sent there for punishement? is the weed not as strong as ours?" 

The Middle one says, "No it's better. Now to earth"

Aohd turns around and a portal opens. Aohd walks threw it returning to Jason.

Jason says, "Hey man you wheren't long" Aohd nods and syas, "I have time to do here on earth. then I got to go to Sector Phi"

Jason gasps and says, "Oh not didn't you say that's hell's hell?" 

Aodh sits on the porch still stuned, "No actualy it's heaven"

Jason sits down and says, "So why are you depressed?"

"Shocked not depressed. I got a title"

"Oh cool"

"Guardian of Earth"

Jason shocked says, "Damn that's huge"

Aohd shakes his head and says, "It's just a title"

Just then rat walks up to Aohd and says, "I was told to delivor you this. I'ts from him"

Aohd confused asks, "Who's him?"

The rat looks around and says, "Him"

Aohd takes the brown back and puls out a rolled up sandwhich bag. When he looks in he sees whitesh leaves with wite fibers over it.

Aohd is amazed and says, "I've only heard fable of this" He looks up and the rat is gone.

JAson asks, "What is it?" 

Aohd with a smile answers, "The best weed in the universe"

Jason happily says, "Nice so it's the good shit of hell weed?"

Aohd shakes his head and syas, "No better than that"
