#+AUTHOR: JoshP1
#+DISCRIPTION: Aohd remembers he's in cult

* Aohd visits the cult
Jason and Aohd are walking threw a alley drinking a bottle of rum. Jason who's staggering a bit says, "Man you make me look like a light weight how do you do it?" Aohd shrugs and says, "No idea I just hear a hissing noise coming from 
inside me.

Jason shakes his head and says, "So you can't get drunk because you burn off everything?" Aohd nods. Jason gets a big smile and says, "How about trying some efuel. It's a higher grade than anything we can buy because well it'd burn a 
whole in someone's stomach.

They sneek into a parkinglot of a gas station. Jason points to to a lone tank and says, "There the efuel tank" Aohd nods and walks over. Puts some money into the meter and puts the nozzle in his beak and begins pumping. 

Jason says, "Dude your glowing" Aohd stops and puts the nozzle back in it's place before burping. He staggers a bit and says, "So this is what it feels like to get drunk" Jason nods and says, "Yeah it's great ain't it?" 

Aohd replies, "So we have to decide between geting drunk. Which is basicly you feel funny and everything spins" Jason fills in, "And feel like shit the next day" Aohd continues, "Verses geting very relaxed and wanting to eat" Jason
again interrupts, "And you feel better the next day" Aodh sahkes his head and staggers back home.

Jason thrwos up three times on the way. Aohd still is hung up on it and says, "Why is the one that makes you feel like shit the next day legal and the other that don't do that. Is illegal" Jason laughs and says, "Because it's a 
consperacy man. You see if it don't kill you they won't legalize it. But if it can kill you they won't outlaw it" Aohd replies, "Then why is hirion and meth illegal?" Jason answers, "It's to drive teh price up so they get rich"

Aohd nods and says, "Thinks make more since when your stoned" He pulls out a joint and begins smoking it.

They make it home. Aohd sits down and says, "Ok so now I'm relaxed and everything is still spinning" Jason just laughs and says, "Thanks for sharing man" Aohd looks up and says, "I didn't dude you where just down wind" Aohd laughs and
says, "So you have to drink efuel to get drunk because it burns off to fast. But need a lighter to light a joint" Aohd replies, "What's a lighter?" Jason shows him his. Aohd laughs and says, "I just hold it in my wing and take a hit. 
It lights it'self"

Jason shakes his head and says, "I need to go in" Aohd waves him off and gets up.

He walks down the street till he sees a bunch of penguins standing around. Aohd's eyes glaze over and he walks up saying, "Hooba dooba woba" One penguin looks up and says, "Hey your that odd bird that joined us last time when we where 
drunk" Aohd replies, "Hooba sooba tooba" One penguin wobbles up and says, "Amazing that looks like the mythical pheonix" Another walks up and says, "That's impossible Synabel. Pheonix simply don't exist" The first penguin, replies, 
"Maybe he can't threw that portal to that hot place we opened up" Suddenly Aohd snaps out of it and asks, "What? What kind of portal?" The penguins are shocked and says, "He can talk" Aohd replies, "Talking penguins this is a first"
One in a lab coat walks up and says, "What are you all doing?" He then looks at Aohd and says, "What do we have here?"

Aohd sticks his chest out in pride and says, "I'm Aohd, gardian of the gate. Well gardian of Earth" The first penguin that talked says, "Gardian of the Gate? What kind of gate" The one in the lab coat that seems to be the leader. 
Asks, "What are you?" Aohd smiles and says, "I am a Pheonix" the penguins laugh and says, "Come on phoenixs are a myth. Prove your a phoenix" Aohd shrugs and jumps up flapping his wings. He suddenly burst into flames. 

He soards around them a bit before landing again. All penguins say, "Amazing", in unison. The lead penguin walks up and says, "Hello I'm Zzyzx" Aohd nods and says, "I'm Aohd" Zzyzx asks, "So Aohd what are you doing on earth?" Aohd
replies, "I live with a goat named Jason but I came here after finding a portal somoene had opened near Hampton street road. I then decided to stay. But was caught by them and had got somoene to delivor me to them. I wasn't terminated
but instead was stationed here"

Zzyzx replies, "Who's they and where is the place your from?" Aohd answers, "The ones I call them are demons or infidials. And we're from Hell" The first penguin shakes his head and says, "Hell is a myth" Aohd rolls his eyes and waves his
wing while chanting somehting in a strange tounge" After he's done a portal opens. The penguin jump back and the first one says, "Damn it's hot. What is that" Aohd replies, "A portal to Hell" Right then a tentical reaches out with a 
roar. Aohd gulps and says something and the portal closes to the monster screaming as it's tentical gets sucked back threw.

Aohd looks and says, "Now? What kind of a cult are you?" Zzyzx replies, "Cult? What do we sound like something a drunk on a forum came up with?" Aohd shrugs and says, "Why did I have to give blood?" Zzyzx replies, "Because we where 
taking blood samples to test how fast the alcohal entered your system. WHen I analyzed yours I couldn't tell what you where. Now I know" 

Aohd a little disappointed says, "Well what about that portal you talked about earlier?" Zzyzx replies, "There seems to been a portal open up in out lab." Aohd nods and says, "It's important I close that portal" The penguins nod and 
lead Aohd to thier labatory.

Along the way the first one that said anything says, "So why are this portals opening" Aohd shrugs and says, "See there is mulitble universes some call relms but the main two near us. The first one is right next to use. So close the
wall can be said is paper thin. The other is better securied" Synabel nods and asks, "So what is it like there?" Aohd replies, "If your born there it kicks ass. But if your not. It is your worse nightmare. The fumes make you 
hulisinate and you have a bad trip  ever time. The heat is unimaginably hot. Also random beast will kick you punch you. Rape you. Basicly do anything they want. But if your a infidel in other words someone that is bad that died
and ended up there. basicly only has the rite to run and that's only because some of the demons like to chase them.

They walk downto the basement of the lab and see a big glowing portal floating above the floor. Aohd waves his wing and speaks the language again. But ntohing happens. So he holds up both of his wings and start yelling out the 
language. 

After a minute Aohd is shaking his head and says, "Strange" Aohd then sighs and says, "I need to chck where this one goes maybe I can close it from the inside."

He climbs in. 

Inside he looks around and sees a what looks like where he's use to but nothing is there. It would b completely bare and dark if it wasn't for the few small lava polls scattered randomly everywhere. He puts his wings up and starts speaking.
But like before nothing happnes.

He looks around for a sign of anything. Before going back threw.

He looks at Zzyzx and says, "Well man it seems somoene or thing more powerful than me made it" Zzyzx don't reply. Aohd then sighs before turning aound and opening his own portal and steps threw it.

He walks up to a man wearing a robe witha  hood covering his face. Aohd bows down and says, "I have a question" The figure nods without saying anything. Aohd asK, "Can I have a favor?" The figure lifts his arm and motions him to go on.

Aohd after sighing says, "I found a portal that I can't close your the most powerful I know. Can you close it?" The figure stands up and his hood falls revieling a penguin. Aohd blinks he looks jsut like Zzyzx except in revirse and his
eyes are glowing red.

He puts the hood back on. Him and Aohd both walk threw the portal aohd opened.

WIthout a word teh hooded penguin walks over to the other portal and in a low growled voice says, "Is this it?" Aohd nods.

The evil penguin then lifts up his wings and begins chanting in a low rowred language. The portal begins flickering and shaking. The penguin begins chanting louder. But protal begins shaking  harder and harder as the penguin chants louder
and louder. Finally after a minute the penguin looks at Aohd and says, "Someone more powerful than I did this" he then walks back to Aohd's portal and disappears. 

After Aohd closes it he turns to Zzyzx and says, "He is the most powerful I know. The next up is a demon and trust me you don't want those freloaders here" Zzyzx nods and says, "So what is the danger of it staying open?" Aohd shrugs and 
says, " It opens to a pretty docolate area. So the fact someoen would of wanted to go there. Is shocking, and I doubt someoen as powerful as it would want to excape. 

Aohd paces back and forth saying something is missing. He perks up and says, "I know" the then goes home returning a few mintues later wear detective gear. Zzyzx blinks and says, "OK lets go. So is that oging to hlep?" Aohd shrugs and 
says, "I always see them earing it on TV. Now I just need to find someone to punch and scream at to get info" 

He pulls out a magnifing glass and begins looking around the room. He also begins picking up things and sticking them in plastic bags. The penguins watch him curiously.

After a few minutes aohd walks up and says, "ok I found a button. A used condom. and a thread does anything seem out of place?" Zzyzx blinks and says, "Well for one we're penguins why would we need condoms?" Aohd nods adn throws 
everything away." Zzxzx asks, "Why did you just throw away that. It seems like someone broke in here. We will need that for evidence" Aohd shrugs and says, "make up your mind. One second you say you won't need it the other second you 
don't"

He then gets it and hands it to Zzyzx. Zzyzx nods and says, "I'll call the cops" Aohd points to the portal and says, "How are you going to explain this?" Zzyzx nods and says, "Man, so do you know someoen more powerful than the evil
penguin" Aohd shrugs and says, "Not that can come here. There is Bob but he don't really do anything but get in the way" Zzyzx nods and asks, "So how do we get him?" Aohd sighs and says, "I guess I can put a portal on the ground and
he can sliver in here" Zyzzx replies confused, "Sliver? What is he a snake?" Aohd replies, "No a blob to be exact. And I'm not sure how he can do anything. He don't have hands"

Another penguin walks up and says, "You said that the walls between this and the other world is pretty thin. What happens if it gets to close and causes a rip"?  Aohd puts up his wing and says something else in a strange language.
Suddenly the portal closes. He looks and says, "That will happen" he then says the same thing back words and waves his wing again and it reopens.

Zzyzx looks and says, "Aohd do that again" Aohd open and closes it again". Zzyzx puts his wing over his face and says, "I ment close it and leave it close" Aohd nods and says, "Why didn't you just say so". Aohd closes teh portal and
says, "Huh guess no one opened it" The penguins shake their haeds. Zzyzx though looks and says, "You could come in handy sometime. Do you mind if we you call you something?" Aohd shrugs and says, "WHat do you want to call me?" Zzyzx 
sighs and says, "Call you if we need your help?" Aohd shrugs and says, "Sure"

They walk him outside and thanks him. Then Aohd goes home. 

Jason walks out and says, "Hey man. Where'd you go?" Aohd says, "I helped my cult close a portal to hell that come to fine out wasn't a portal but a simple fracture in the structure of space and time. Jason blinks and says, "How did you
do that?" Aohd shrugs and says, "I pointed at it and said close damn it. In demon"
